// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pubg-miniapp/MiniApp.tsx": () => import("../components/mockups/pubg-miniapp/MiniApp.tsx"),
  "./components/mockups/pubg-miniapp/Redesign.tsx": () => import("../components/mockups/pubg-miniapp/Redesign.tsx")
};
